#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <master-password>"
    exit 1
fi

password=$1
encrypted_password=$(mvn --encrypt-master-password "$password")

if [ ! -d "$HOME/.m2" ]; then
  mkdir "$HOME/.m2"
fi

cat > "$HOME/.m2/settings-security.xml" <<EOF
<settingsSecurity>
  <master>${encrypted_password}</master>
</settingsSecurity>
EOF

echo "The encrypted master password has been saved to $HOME/.m2/settings-security.xml"
